import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell } from "recharts";
import { mockLeadFunnel, mockLeadSources } from "@/lib/mockAnalytics";

export function LeadsSection() {
  const funnelColors = ["#3B82F6", "#06B6D4", "#22C55E", "#FACC15", "#15803D"];

  return (
    <div className="space-y-4">
      <h2 className="text-2xl font-semibold">Lead Analytics</h2>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Lead Funnel */}
        <Card>
          <CardHeader>
            <CardTitle>Lead Funnel</CardTitle>
            <CardDescription>Conversion through stages</CardDescription>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={300}>
              <BarChart data={mockLeadFunnel}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="stage" />
                <YAxis />
                <Tooltip />
                <Bar dataKey="value" radius={[8, 8, 0, 0]}>
                  {mockLeadFunnel.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={funnelColors[index]} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        {/* Lead Source Performance */}
        <Card>
          <CardHeader>
            <CardTitle>Lead Source Performance</CardTitle>
            <CardDescription>Leads generated by source</CardDescription>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={300}>
              <BarChart data={mockLeadSources}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="source" />
                <YAxis />
                <Tooltip />
                <Bar dataKey="leads" fill="#06B6D4" radius={[8, 8, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        {/* Lead Response Time */}
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>Lead Response Metrics</CardTitle>
            <CardDescription>Average response times and engagement</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
              <div className="p-4 bg-muted rounded-lg">
                <div className="text-2xl font-bold">2m 34s</div>
                <div className="text-sm text-muted-foreground">Avg First Response</div>
              </div>
              <div className="p-4 bg-muted rounded-lg">
                <div className="text-2xl font-bold">8m 12s</div>
                <div className="text-sm text-muted-foreground">Avg Follow-up Time</div>
              </div>
              <div className="p-4 bg-muted rounded-lg">
                <div className="text-2xl font-bold">72%</div>
                <div className="text-sm text-muted-foreground">Response Rate</div>
              </div>
              <div className="p-4 bg-muted rounded-lg">
                <div className="text-2xl font-bold">4.2</div>
                <div className="text-sm text-muted-foreground">Avg Touches to Close</div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
